# Generated by Django 3.0.11 on 2024-12-11 12:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('discount_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'coupon',
            },
        ),
    ]
